const countries_EU = [
    ["Belgium", "BE"],
    ["Greece", "EL"],
    ["Lithuania", "LT"],
    ["Portugal", "PT"],
    ["Bulgaria", "BG"],
    ["Spain", "ES"],
    ["Luxembourg", "LU"],
    ["Romania", "RO"],
    ["Czechia", "CZ"],
    ["France", "FR"],
    ["Hungary", "HU"],
    ["Slovenia", "SI"],
    ["Denmark", "DK"],
    ["Croatia", "HR"],
    ["Malta", "MT"],
    ["Slovakia", "SK"],
    ["Germany", "DE"],
    ["Italy", "IT"],
    ["Netherlands", "NL"],
    ["Finland", "FI"],
    ["Estonia", "EE"],
    ["Cyprus", "CY"],
    ["Austria", "AT"],
    ["Sweden", "SE"],
    ["Ireland", "IE"],
    ["Latvia", "LV"],
    ["Poland", "PL"],
    // EFTA members
    ["Iceland", "IS"],
    ["Norway", "NO"],
    ["Liechtenstein", "LI"],
    ["Switzerland", "CH"],
    // EU candidates
    ["Bosnia and Herzegovina", "BA"],
    ["Montenegro", "ME"],
    ["Moldova", "MD"],
    ["North Macedonia", "MK"],
    ["Georgia", "GE"],
    ["Albania", "AL"],
    ["Serbia", "RS"],
    ["Türkiye", "TR"],
    ["Ukraine", "UA"],
];

export const countryCodes_EU = countries_EU.map((country) => country[1]);
